### ISSUE TITLE
ENgettimeparam function (epanet.c)

### ISSUE THREAD

**Issue by mauriziocingi** [OpenWaterAnalytics/Water-Distribution-Network-Model#2]
ENgettimeparam function (line 1087 of epanet.c) doesn't recognize EN_RULESTEP code and
always returns 0 

A line like 
case EN_RULESTEP:      *value = Rulestep;     break;
has to be added

Also code=12 (EN_HALTFLAG) in the interval EN_DURATION - EN_NEXTEVENT is not managed by ENgettimeparam

**Comment by samhatchett** [comment]
implementing this in the object-wrapped branch, which is where future development is going anyway; this is fully backward-compatible with previous client code.
